# ===============================
# Starship config (cross-platform)
# Mirrors your OMP theme:
#  - user@host "on" path
#  - DOTNET_VERSION (from env)
#  - python / node versions
#  - git head + ahead/behind + changes + stash
#  - clock + green ❯ on the next line
# ===============================

# Two-line prompt: main line + time + symbol
format = """
$os$username[@](bold cyan)$hostname(bold cyan) on $directory \
$env_var$python$nodejs$git_branch$git_status
$time$character
"""

# Use nerd fonts for symbols (recommended)
add_newline = true

[os]
disabled = true

[username]
style = "bold #45F1C2"
format = "[$user]($style)"
show_always = true

[hostname]
style = "bold #45F1C2"
ssh_only = false
format = "[$hostname]($style)"

[directory]
style = "#0CA0D8"
truncation_length = 4
truncation_symbol = "…/"
read_only = " "
format = "[$path]($style) "

[env_var.DOTNET_VERSION]
# shows like:   net8.0
style = "magenta"
symbol = " "
format = "[${symbol}${env_value}]($style) "

[python]
style = "yellow"
symbol = " "
format = "[${symbol}${version}]($style) "
pyenv_version_name = false

[nodejs]
style = "cyan"
symbol = " "
format = "[${symbol}${version}]($style) "

[git_branch]
symbol = " "
style = "#14A5AE"
format = "[${symbol}${branch}]($style)"

[git_status]
style = "#14A5AE"
format = "[$all_status$ahead_behind]($style) "
conflicted = " "
deleted = " "
modified = " "
stashed = " "
staged = " "
untracked = " "
ahead = " ⇡ ${count}"
behind = " ⇣ ${count}"
diverged = " ⇕ ${ahead_count}/${behind_count}"

[time]
disabled = false
time_format = "%H:%M:%S"
style = "yellow"
format = "[ $time]($style) "

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
